# Use root/mysql as user/password credentials
version: "3.1"
services:
  db:
    image: mysql:5.7.34
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: hbthy
      MYSQL_PASSWORD: hbthy
      MYSQL_DATABASE: hb_thy_db
    ports:
      - 3392:3306
    volumes:
      - mysql-data-mvc:/var/lib/mysql

volumes:
  mysql-data-mvc:
